version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ecommerce-service
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - ecommerce-service
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
    networks:
      - ecommerce-service
  apm:
    image: docker.elastic.co/apm/apm-server:7.13.1
    ports:
      - 8200:8200
    volumes:
      - ./config/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - ecommerce-service
    depends_on:
      - es01
      - es02
      - kibana
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - ecommerce-service
    volumes:
      - ./storage/redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce_2021'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'YuUxc>6J.V%_V4+'
      MYSQL_ROOT_PASSWORD: 'YuUxc>6J.V%_V4+'
    ports:
      - '3306:3306'
    networks:
      - ecommerce-service
    expose:
      - '3306'
    volumes:
      - ./storage/mysql:/var/lib/mysql
  api-server:
    build:
      context: ../
      dockerfile: docker/dockerfile
    restart: always
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/"]
        interval: 30s
        timeout: 1s
        retries: 3
        start_period: 60s
    environment:
      MYSQL_HOST: mysql
      MYSQL_REPLICA_HOST: mysql
      MYSQL_DATABASE: ecommerce_2021
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: YuUxc>6J.V%_V4+
      MYSQL_PORT: '3306'
      REDIS_HOST: redis
      REDIS_PASSWORD: ''
      REDIS_PORT: '6379'
      ELASTIC_APM_SERVICE_NAME: ecommerce-api-server
      ELASTIC_APM_SERVER_URL: http://apm:8200
      ELASTIC_APM_ACTIVE: 'true'
    ports:
      - '3000:3000'
    networks:
      - ecommerce-service
    depends_on:
      - mysql
      - redis
      - apm
    command: npm run start:prod
volumes:
  data01:
    driver: local
  data02:
    driver: local
networks:
  ecommerce-service:
    driver: bridge
