version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - eak
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - eak
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
    networks:
      - eak
  apm:
    image: docker.elastic.co/apm/apm-server:7.13.1
    ports:
      - 8200:8200
    volumes:
      - ./config/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - eak
    depends_on:
      - es01
      - es02
      - kibana
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce_2021'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'YuUxc>6J.V%_V4+'
      MYSQL_ROOT_PASSWORD: 'YuUxc>6J.V%_V4+'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./storage/mysql:/var/lib/mysql

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  eak:
    driver: bridge
